### ISSUE TITLE
Can I use?

### ISSUE THREAD

**Issue by e-coders** [somePythonProgrammer/somepythonprogrammer.github.io#1]
I'd seen the your beautiful blog look. Have I permission to add it to a project I'm working on (blog maker). I will also give you contribution badge. Am I able to use it?

**Comment by somePythonProgrammer** [comment]
Sure! It was designed with Bootstrap studio. Go ahead!

**Comment by somePythonProgrammer** [comment]
BTW I would love to see your project. Will you send me the link on this issue when it's done?

**Comment by e-coders** [comment]
Thanks! I will send the full project once completed. You might also love it as well! Its made in my 8 hours of 3 days!

**Comment by e-coders** [comment]
I can now feel how you develop great projects, Like PyCraft and JARVIS....!

**Comment by e-coders** [comment]
I succeed! Lets do some final things! The project 'blog maker' is working properly and can save posts, But the last thing is to show 'No Posts found' when there have 0 posts on home.

**Comment by somePythonProgrammer** [comment]
I am working on a blog post on adding blocks to PyCraft right now.

**Comment by e-coders** [comment]
Success! Everything done! Now time to publish!

**Comment by e-coders** [comment]
Finally, Uploading to e-coders/BlogMaker

**Comment by e-coders** [comment]
17 files

**Comment by e-coders** [comment]
When done everything uploading, will say.

**Comment by e-coders** [comment]
Finally, Success! See the readme https://github.com/e-coders/BlogMaker

**Comment by e-coders** [comment]
If you have any issues, Just message me!

**Comment by somePythonProgrammer** [comment]
It's pretty good!

**Comment by e-coders** [comment]
Thanks so much!

**Comment by somePythonProgrammer** [comment]
Also, you can just publish it to github pages, so that people can get a quick preview of it. Add the link to the readme.

**Comment by e-coders** [comment]
Try out, easily post posts to your blog!

**Comment by e-coders** [comment]
Ok, sure!

**Comment by e-coders** [comment]
I will create a new branch for it.

**Comment by somePythonProgrammer** [comment]
> Try out, easily post posts to your blog!

Sure!

**Comment by e-coders** [comment]
YAY

**Comment by e-coders** [comment]
Here's the Sample of blog!
https://e-coders.github.io/BlogMaker/
To edit, download.

**Comment by e-coders** [comment]
wait, uploading

**Comment by somePythonProgrammer** [comment]
The site shows only the readme. Make sure you add `index.html` in the root directory, and redirect them to `/site/index.html` immediately, using javascript in a script tag:
`window.location.replace('https://link-to-file')`

**Comment by e-coders** [comment]
Yes, I know, Just wait uploading files.

**Comment by e-coders** [comment]
Now, Visit the website!

**Comment by e-coders** [comment]
Finally done! https://e-coders.github.io/BlogMaker/

**Comment by somePythonProgrammer** [comment]
I've added a PR. please merge it.

**Comment by somePythonProgrammer** [comment]
It has a new feature and many docstrings.

**Comment by e-coders** [comment]
Yes. Thanks so much!

**Comment by e-coders** [comment]
I notice some issues, So I now updated. Fetch all new commits to your repo to avoid conflicts

**Comment by e-coders** [comment]
Woah, You made your blog really great. For info about how to delete a post, say.

**Comment by e-coders** [comment]
Hi dude, also see! I got e-coders.me as with github student developer pack! thanks so much!

**Comment by N3RDIUM** [comment]
@e-coders Hey there, I've upgraded the look of the site, and put it on a domain. How does it look now?
https://n3rdium.dev
